# Generated by Django 4.2.30 on 2026-07-03 02:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('play_sessions', '0002_add_active_segment_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('qris', 'QRIS'), ('e_wallet', 'E-Wallet'), ('card', 'Card')], default='cash', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='paid', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gateway_reference', models.CharField(blank=True, default='', max_length=255)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments_created', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='play_sessions.playsession')),
            ],
            options={
                'ordering': ['-paid_at'],
                'indexes': [models.Index(fields=['session'], name='payments_pa_session_b36361_idx'), models.Index(fields=['created_by'], name='payments_pa_created_6e4470_idx'), models.Index(fields=['paid_at'], name='payments_pa_paid_at_b40014_idx')],
            },
        ),
    ]
