# Generated by Django 4.2.30 on 2026-07-02 02:02

from django.db import migrations


def seed_roles_and_permissions(apps, schema_editor):
    Role = apps.get_model('users', 'Role')
    Permission = apps.get_model('users', 'Permission')

    # Create Permissions
    permission_defs = [
        ('crud_tenant', 'CRUD Tenant', 'Create, read, update, delete tenant'),
        ('crud_outlet', 'CRUD Outlet', 'Create, read, update, delete outlet'),
        ('crud_user_admin_officer', 'CRUD User (Admin/Officer)', 'Manage admin and officer users in own outlet'),
        ('crud_table', 'CRUD Table', 'Create, read, update, delete tables'),
        ('crud_pricing_rule', 'CRUD Pricing Rule', 'Create, read, update, delete pricing rules'),
        ('crud_package', 'CRUD Package', 'Create, read, update, delete packages'),
        ('manage_play_session', 'Manage Play Session', 'Start/stop sessions, transfer table'),
        ('print_receipt', 'Print Receipt', 'Print/cetak receipt'),
        ('view_history_session', 'View History Session', 'View session history'),
        ('view_dashboard_insight', 'View Dashboard Insight', 'View dashboard and business insights'),
        ('manage_shift', 'Manage Shift', 'Open and close shift'),
        ('view_audit_log', 'View Audit Log', 'View audit log in own outlet'),
    ]

    permissions = {}
    for codename, name, desc in permission_defs:
        perm, _ = Permission.objects.get_or_create(codename=codename, defaults={'name': name, 'description': desc})
        permissions[codename] = perm

    # Create Roles
    super_admin, _ = Role.objects.get_or_create(
        name='super_admin',
        defaults={'description': 'Super Admin — manage all tenants and outlets'},
    )
    super_admin.permissions.add(
        permissions['crud_tenant'],
        permissions['crud_outlet'],
        permissions['crud_user_admin_officer'],
    )

    owner, _ = Role.objects.get_or_create(
        name='owner',
        defaults={'description': 'Owner — view dashboard and history across outlets in own tenant'},
    )
    owner.permissions.add(
        permissions['view_history_session'],
        permissions['view_dashboard_insight'],
    )

    admin, _ = Role.objects.get_or_create(
        name='admin',
        defaults={'description': 'Admin — manage outlet config, users, and view reports'},
    )
    admin.permissions.add(
        permissions['crud_user_admin_officer'],
        permissions['crud_table'],
        permissions['crud_pricing_rule'],
        permissions['crud_package'],
        permissions['print_receipt'],
        permissions['view_history_session'],
        permissions['view_dashboard_insight'],
        permissions['view_audit_log'],
    )

    officer, _ = Role.objects.get_or_create(
        name='officer',
        defaults={'description': 'Officer — daily operations'},
    )
    officer.permissions.add(
        permissions['manage_play_session'],
        permissions['print_receipt'],
        permissions['view_history_session'],
        permissions['manage_shift'],
    )


def reverse_seed(apps, schema_editor):
    Role = apps.get_model('users', 'Role')
    Permission = apps.get_model('users', 'Permission')

    seeded_role_names = ['super_admin', 'owner', 'admin', 'officer']
    seeded_permission_codenames = [
        'crud_tenant', 'crud_outlet', 'crud_user_admin_officer',
        'crud_table', 'crud_pricing_rule', 'crud_package',
        'manage_play_session', 'print_receipt',
        'view_history_session', 'view_dashboard_insight',
        'manage_shift', 'view_audit_log',
    ]

    Role.objects.filter(name__in=seeded_role_names).delete()
    Permission.objects.filter(codename__in=seeded_permission_codenames).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_roles_and_permissions, reverse_seed),
    ]