# Generated by Django 4.2.30 on 2026-07-03 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_seed_roles_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('cancel_session', 'Cancel Session'), ('open_shift', 'Open Shift'), ('close_shift', 'Close Shift')], max_length=32)),
                ('object_type', models.CharField(max_length=64)),
                ('object_id', models.IntegerField(blank=True, null=True)),
                ('changes', models.JSONField(default=dict)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('outlet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='users.outlet')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='audit_logs__user_id_d31e2a_idx'), models.Index(fields=['outlet', 'created_at'], name='audit_logs__outlet__d14fbd_idx'), models.Index(fields=['action', 'created_at'], name='audit_logs__action_70fdcf_idx'), models.Index(fields=['object_type', 'object_id'], name='audit_logs__object__7039e2_idx')],
            },
        ),
    ]
