# Generated by Django 4.2.30 on 2026-07-02 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shifts', '0001_initial'),
        ('packages', '0001_initial'),
        ('users', '0002_seed_roles_permissions'),
        ('tables', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(blank=True, default='', max_length=20)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='running', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, help_text='Total biaya permainan (sum table_log amounts atau fixed_price package).', max_digits=12, null=True)),
                ('additional_fee_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cancel_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('initial_table', models.ForeignKey(help_text='Meja pertama saat sesi dibuka.', on_delete=django.db.models.deletion.PROTECT, related_name='play_sessions', to='tables.table')),
                ('officer_end', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_ended', to=settings.AUTH_USER_MODEL)),
                ('officer_start', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions_started', to=settings.AUTH_USER_MODEL)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='play_sessions', to='users.outlet')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='play_sessions', to='packages.package')),
                ('shift', models.ForeignKey(help_text='Shift aktif officer saat sesi dibuka.', on_delete=django.db.models.deletion.PROTECT, related_name='play_sessions', to='shifts.shift')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionTableLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_source_type', models.CharField(choices=[('pricing_rule', 'Pricing Rule'), ('package_rate', 'Package Rate')], max_length=20)),
                ('rate_source_snapshot', models.JSONField(help_text='Salinan tarif yang berlaku saat segmen ini berjalan.')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_logs', to='play_sessions.playsession')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_logs', to='tables.table')),
            ],
            options={
                'ordering': ['started_at'],
                'indexes': [models.Index(fields=['session', 'ended_at'], name='play_sessio_session_4b87a2_idx'), models.Index(fields=['table', 'ended_at'], name='play_sessio_table_i_a209aa_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='playsession',
            index=models.Index(fields=['outlet', 'status'], name='play_sessio_outlet__53abe9_idx'),
        ),
        migrations.AddIndex(
            model_name='playsession',
            index=models.Index(fields=['started_at'], name='play_sessio_started_8b1119_idx'),
        ),
    ]
