# Generated by Django 4.2.30 on 2026-07-03 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='sessiontablelog',
            constraint=models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('session',), name='uq_active_segment_per_session', violation_error_message='Session already has an active segment.'),
        ),
        migrations.AddConstraint(
            model_name='sessiontablelog',
            constraint=models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('table',), name='uq_active_segment_per_table', violation_error_message='Table is already in use by another active session segment.'),
        ),
    ]
