# Generated by Django 4.2.30 on 2026-07-03 02:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_seed_roles_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('play_sessions', '0002_add_active_segment_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('pdf_file', models.FileField(upload_to='receipts/%Y/%m/')),
                ('printed_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('printed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts_printed', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='play_sessions.playsession')),
            ],
            options={
                'verbose_name': 'Receipt',
                'verbose_name_plural': 'Receipts',
                'ordering': ['-printed_at'],
                'indexes': [models.Index(fields=['session'], name='receipts_re_session_04810e_idx'), models.Index(fields=['printed_by'], name='receipts_re_printed_12f30f_idx'), models.Index(fields=['printed_at'], name='receipts_re_printed_daffe1_idx')],
            },
        ),
        migrations.CreateModel(
            name='InvoiceSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_sequence', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_sequences', to='users.outlet')),
            ],
            options={
                'verbose_name': 'Invoice Sequence',
                'verbose_name_plural': 'Invoice Sequences',
                'unique_together': {('outlet', 'date')},
            },
        ),
    ]
