# Generated by Django 4.2.30 on 2026-07-02 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_seed_roles_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('per_minute', 'Per Minute'), ('fixed_duration', 'Fixed Duration'), ('open_loss', 'Open Loss'), ('happy_hour', 'Happy Hour')], max_length=20)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('fixed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_per_minute', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valid_day_type', models.CharField(choices=[('all', 'All Days'), ('weekday', 'Weekday'), ('weekend', 'Weekend'), ('specific_day', 'Specific Day')], default='all', max_length=20)),
                ('specific_date', models.DateField(blank=True, null=True)),
                ('valid_start_time', models.TimeField(blank=True, null=True)),
                ('valid_end_time', models.TimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='users.outlet')),
            ],
            options={
                'ordering': ['outlet', 'name'],
                'unique_together': {('outlet', 'name')},
            },
        ),
    ]
